fake_csv/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("test_task.urls", namespace="test_task")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

test_task/urls.py
from django.urls import path

from .views import (
    SchemaListView,
    SchemaCreateView,
    SchemaEditView,
    DataSetsView,
    Login,
    SchemaDeleteView,
    ColumnsDeleteViews,
)

urlpatterns = [
    path("", Login.as_view(), name="index"),
    path("schemas/", SchemaListView.as_view(), name="schema-list"),
    path("schemas/create/", SchemaCreateView.as_view(), name="schema-create"),
    path("schemas/edit/<int:pk>/", SchemaEditView.as_view(), name="schema-edit"),
    path(
        "schemas/delete/<int:pk>/",
        SchemaDeleteView.as_view(),
        name="schema-delete",
    ),
    path("schemas/<int:pk>/", DataSetsView.as_view(), name="schema-detail"),
    path(
        "columns/<int:pk>/delete/", ColumnsDeleteViews.as_view(), name="columns-delete"
    ),
]

app_name = "test_task"

test_task/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse


class Schema(models.Model):

    DELIMITERS = [
        (",", "Comma(,)"),
        (";", "Semilicon(;)"),
        (" ", "Space( )"),
        ("|", "Pipe(|)"),
    ]

    QUOTES = [
        ('"', 'Double-quote(")'),
        ("'", "Single-quote(')"),
    ]

    title = models.CharField(max_length=63, blank=True, null=True)
    column_separator = models.TextField(choices=DELIMITERS, default=",", max_length=1)
    string_character = models.TextField(choices=QUOTES, default='""', max_length=1)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name="schemas"
    )

    def get_absolute_url(self):
        return reverse("test_task:schema-detail", kwargs={"pk": self.id})

    class Meta:
        ordering = ["-updated"]


class Column(models.Model):

    DATA_TYPES = [
        ("Full_name", "Full name"),
        ("Job", "Job"),
        ("Email", "Email"),
        ("Domain_name", "Domain name"),
        ("Phone_number", "Phone number"),
        ("Company_name", "Company name"),
        ("Text", "Text"),
        ("Integer", "Integer"),
        ("Address", "Address"),
        ("Date", "Date"),
    ]

    column_name = models.CharField(max_length=20)
    data_type = models.CharField(max_length=20, choices=DATA_TYPES)
    order = models.PositiveIntegerField(default=0)
    schema = models.ForeignKey(
        to=Schema, on_delete=models.CASCADE, related_name="schemacolumns"
    )

    class Meta:
        ordering = ["order"]

    def clean(self):
        super(Column, self).clean()
        if not self.order:
            self.order = Column.objects.filter(schema=self.schema).count() + 1


class DataSet(models.Model):
    STATUSES = [(0, "Processing.."), (1, "Ready!")]
    schema = models.ForeignKey(
        to=Schema, on_delete=models.CASCADE, related_name="schemadatasets"
    )
    created = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUSES, default=0)
    rows = models.PositiveIntegerField(null=True)
    download_link = models.URLField()

    class Meta:
        ordering = ["-created"]

test_task/forms.py
from django import forms
from extra_views import InlineFormSetFactory

from test_task.models import Schema, Column, DataSet


class SchemaForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Write name of schema"})
    )

    class Meta:
        model = Schema
        fields = "__all__"
        widgets = {"user": forms.HiddenInput()}


class ColumnForm(forms.ModelForm):
    column_name = forms.CharField(
        widget=forms.TextInput(attrs={"placeholder": "Write column name"}),
    )

    class Meta:
        model = Column
        fields = "__all__"


class SchemaColumnInline(InlineFormSetFactory):
    model = Column
    form_class = ColumnForm

    fields = "__all__"

    factory_kwargs = {
        "extra": 1,
        "max_num": None,
        "can_order": False,
        "can_delete": False,
    }


class DataSetForm(forms.ModelForm):
    rows = forms.CharField(
        required=True,
        widget=forms.TextInput(attrs={"placeholder": "input rows"}),
    )

    class Meta:
        model = DataSet
        fields = ("rows",)

test_task/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse, HttpRequest, FileResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.edit import FormMixin, DeleteView
from extra_views import CreateWithInlinesView, UpdateWithInlinesView
from test_task.utils import generate_csv_file

from test_task.forms import (
    SchemaForm,
    SchemaColumnInline,
    DataSetForm,
)
from test_task.models import Schema, DataSet, Column


class Login(LoginView):
    template_name = "registration/login.html"
    redirect_authenticated_user = True


class SchemaListView(LoginRequiredMixin, generic.ListView):
    model = Schema
    queryset = Schema.objects.all()
    template_name = "core/schema_list.html"

    def get_queryset(self):
        queryset = Schema.objects.filter(user=self.request.user)
        return queryset


class SchemaCreateView(LoginRequiredMixin, CreateWithInlinesView):
    model = Schema
    form_class = SchemaForm
    inlines = [
        SchemaColumnInline,
    ]
    template_name = "core/schema_form.html"

    def get_initial(self):
        return {"user": self.request.user}

    def get_success_url(self):
        if "action" in self.request.POST:
            if self.request.POST["action"] == "add_column":
                return reverse_lazy(
                    "test_task:schema-edit", kwargs={"pk": self.object.pk}
                )
            if self.request.POST["action"] == "submit":
                return reverse_lazy("test_task:schema-list")
        return reverse_lazy("test_task:schema-list")


class SchemaEditView(LoginRequiredMixin, UpdateWithInlinesView):
    model = Schema
    form_class = SchemaForm
    inlines = [
        SchemaColumnInline,
    ]
    template_name = "core/schema_form.html"

    def get_success_url(self):
        if "action" in self.request.POST:
            if self.request.POST["action"] == "add_column":
                return reverse_lazy(
                    "test_task:schema-edit", kwargs={"pk": self.object.pk}
                )
            if self.request.POST["action"] == "submit":
                return reverse_lazy("test_task:schema-list")
        return reverse_lazy("test_task:schema-list")


class SchemaDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Schema
    template_name = "core/schema_confirm_delete.html"

    def get_success_url(self):
        return reverse_lazy("test_task:schema-list")


def is_ajax(request):
    return request.META.get("HTTP_X_REQUESTED_WITH") == "XMLHttpRequest"


class DataSetsView(LoginRequiredMixin, FormMixin, generic.DetailView):
    model = Schema
    form_class = DataSetForm
    template_name = "core/datasets.html"

    def get_context_data(self, **kwargs):
        context = super(DataSetsView, self).get_context_data()
        schema = self.get_object()
        columns = schema.schemacolumns.all()
        context["columns"] = columns
        return context

    def post(self, request, *args, **kwargs):
        schema = self.get_object()
        dataset = DataSet.objects.create(schema=schema, rows=int(request.POST["rows"]))

        if is_ajax(request):
            generate_csv_file(dataset)

            html = render_to_string(
                "core/table.html",
                context={"schema": schema},
                request=request,
            )

            return JsonResponse({"msg": html})

        return HttpResponseRedirect(
            reverse_lazy("test_task:schema-detail", kwargs={"pk": schema.pk})
        )


class ColumnsDeleteViews(LoginRequiredMixin, generic.DeleteView):
    model = Column
    success_url = reverse_lazy("test_task:schema-create")

templates/base.html
<!DOCTYPE html>
<html lang="en">
   <head>
      {% block title %}{% endblock %}
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link
        href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.0/mdb.min.css"
        rel="stylesheet">
    <script
      type="text/javascript"
      src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/6.0.0/mdb.min.js">
    </script>
     <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
     <script src="https://unpkg.com/htmx.org@1.8.5" integrity="sha384-7aHh9lqPYGYZ7sTHvzP1t3BAfLhYSTy9ArHdP3Xsr9/3TlGurYgcPBoFmXX2TX/w" crossorigin="anonymous"></script>

   </head>
   <body>
      {% include 'includes/navbar.html' %}
      <div class="container-sm" style="margin-top: 50px">
         {% block content %} {% endblock %}
      </div>


   </body>
</html>

templates/core/datasets.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block title %}
  <title>Datasets</title>
{% endblock %}

{% block content %}

<h1>Sample schema {{ schema.title }}
  <a href="{% url 'test_task:schema-edit' schema.id %}" class="btn btn-link">Edit</a>
</h1>
{% if columns %}
  <table class="table table-striped-columns">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Column Name</th>
        <th scope="col">Column Type</th>
      </tr>
    </thead>

    <tbody>
    {% for column in columns %}
      <tr>
        <th>{{ column.order }}</th>
        <td>{{ column.column_name }}</td>
        <td>{{ column.data_type }}</td>
      </tr>

      {% endfor %}
    </tbody>
  </table>
{% else %}
    <p class="lead">No columns</p>
{% endif %}


<form method="post" id="upload_form">
  {% csrf_token %}

  {{ form.rows }}

  <button type="submit" class="btn btn-primary" >Generate data</button>
</form>
<br>
  <h2>Data sets of {{ schema.title }}</h2>
  <div id="datasets">
    {% include 'core/table.html'%}
  </div>

  <script>
    $(document).ready(function () {
        $(document).on('submit', '#upload_form', function (e) {
            e.preventDefault();
            const newRow = `<tr>
      <th scope="row">${$('#table tbody tr').length + 1}</th>
      <td>${new Date().toLocaleString()}</td>
      <td><span class="badge badge-danger">Proccesing</span></td>
      <td></td>
    </tr>`;
            $('#table tbody').prepend(newRow);

            $.ajax({
                type: "POST",
                url: "{% url "test_task:schema-detail" schema.pk %}",
                data: {
                    rows: $('#id_rows').val(),
                    csrfmiddlewaretoken: '{{ csrf_token }}',
                    dataType: "json",
                },
                success: function (data) {
                    setTimeout(function () {
                        $('#table tbody tr:first-child td:nth-child(3)').html(`<span class="badge badge-success">Success</span>`);
                        $('#table tbody tr:first-child td:nth-child(4)').html(`<a href="${data.link}" class="btn btn-link">Download</a>`);

                    }, 1000);

                    $(`#datasets`).html(data["msg"])
                    document.getElementById("upload_form").reset()
                },
            });
        });
    });
  </script>

{% endblock %}

templates/core/schema_confirm_delete.html
{% extends 'base.html' %}

{% block title %}
  <title>Confirm delete</title>
{% endblock %}

{% block content %}
<h1>Delete {{ fakeschema.title }}</h1>
<p class="lead">Are you sure you want to delete this schema?</p>
<form action="" method="post">
  {% csrf_token %}
  <input class="btn btn-danger" type="submit" value="Yes, delete">
  <a href="{% url 'test_task:schema-list' %}">
  <input class="btn btn-secondary" value="Cancel">
  </a>
</form>
{% endblock %}

templates/core/schema_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block title %}<title>{{ object|yesno:"Update,Add" }} schema</title>{% endblock %}

{% block content %}

<form action="" method="post" enctype="multipart/form-data">
  <h1>{{ object|yesno:"Update,New" }} schema {% if schema %}{{ schema.title }}{% endif %}
    <a href="{% url 'test_task:schema-list'%}" class="btn btn-link">Back</a>
  </h1>
  <button type="submit" name="action" value="submit" class="btn btn-primary">Submit</button>

  {% csrf_token %} {{ form|crispy }}
  <div style="margin-top: 20px;">
    <h3>Schema columns</h3>
    {% for formset in inlines %}
    <div class="formset">
      {{ formset.management_form|crispy}}
        {% for columnsform in formset %}
        <div class="row flex-nowrap row-cols-lg-auto g-3 align-items-center">
          {{ columnsform|crispy }}
          <div class="delete">
            <button type="button" id="delete_column" class="btn btn-danger" onclick="removeColumn()">Delete</button>
          </div>
        </div>
          {% if forloop.last %}
            <div>
              <button class="btn btn-primary" type="submit" name="action" value="add_column">Add column</button>
            </div>
          {% endif %}
        {% endfor %}
        </div>
      {% endfor %}

  </div>
</form>

  <script>
    const removeColumn = (delete_column) => {
    const element = document.getElementById(delete_column);
    removeColumn(element);
  };
  </script>
{% endblock %}

templates/core/schema_list.html
{% extends "base.html" %}

{% block title %}
<title>Schema list</title>
{% endblock %}

{% block content %}

<h1>
  Data schemas
  <a class="btn btn-primary" href="{% url 'test_task:schema-create' %}">
    Create Schema
    <i class="fas fa-plus"></i>
  </a>
</h1>
  <br>
{% if schema_list %}
<table class="table table-striped-columns">
  <thead class="table-primary">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Title</th>
      <th scope="col">Modified</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  {% for schema in schema_list %}
  <tbody>
    <tr class="text-dark">
      <td>{{ forloop.counter }}</td>
      <td>
        <a class="btn btn-link" href="{{ schema.get_absolute_url }}"> {{ schema.title}}</a>
      </td>
      <td>
        {% if schema.updated %} {{ schema.updated }} {% else %} {{ schema.created }} {% endif %}
      </td>
      <td>
        <a href="{% url 'test_task:schema-edit' pk=schema.id%}" class ="text-decoration-none">Edit schema</a>
        <a href="{% url 'test_task:schema-delete' pk=schema.id%}" class ="text-decoration-none text-danger ms-2">DELETE</a>
      </td>
    </tr>
  </tbody>
  {% endfor %}
</table>
{% else %}
<p>There is no schemas </p>
{% endif %}

{% endblock %}

templates/core/table.html
<table class="table table-strip table-bordered text-center bg-white" id="table">
  <thead class="table-primary">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Created</th>
      <th scope="col">Status</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    {% for dataset in schema.schemadatasets.all %}
    <tr>
      <th scope="row">{{forloop.counter}}</th>
      <td>{{ dataset.created }}</td>
      <td>
        {% if dataset.status == 1 %}
        <span class="badge badge-success">Success</span>
          <td>
        <a href="{{dataset.download_link}}" class="btn btn-link">Download</a>
          </td>
        {%else%}
        <span class="badge badge-danger">Processing...</span>
        {%endif%}
      </tr>
    {% endfor %}
  </tbody>
</table>

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="">CSV Generator</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
                <a class="nav-link" aria-current="page" href="{% url 'test_task:schema-list' %}">Schemas</a>
            </div>
        </div>

        <ul class="navbar-nav justify-content-end">
            <li class="nav-item">
                {% if not user.is_authenticated %}
                <a class="navbar-brand" href="{% url "login" %}">Login</a>
                {% endif %}
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="">Hello, <strong>{{ user.username }}</strong></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>